-- SYS 관리자 계정 이용
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 사용자 계정 생성
CREATE USER sh IDENTIFIED BY sh1234;

-- 생성한 사용자 계정에 권한을 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO sh;


-- 테이블 스페이스 할당
ALTER USER sh DEFAULT 
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;


---------------------------------------------------------------------------
-- sh계정
CREATE TABLE MENU(
	MENU_NO VARCHAR2(30) PRIMARY KEY,
	MENU_NM VARCHAR2(30) NOT NULL,
	MENU_PRICE NUMBER NOT NULL,
	SALES_QUANTITY NUMBER NOT NULL,
	SALES_DATE DATE DEFAULT SYSDATE
);


COMMENT ON COLUMN MENU.MENU_NO IS '메뉴 번호';
COMMENT ON COLUMN MENU.MENU_NM IS '메뉴명';
COMMENT ON COLUMN MENU.MENU_PRICE IS '메뉴 가격';
COMMENT ON COLUMN MENU.SALES_QUANTITY IS '판매 수량';
COMMENT ON COLUMN MENU.SALES_DATE IS '판매 날짜';

DROP TABLE Menu;
SELECT * FROM MENU;


INSERT INTO MENU VALUES('1', '아메리카노', 4500, 2, DEFAULT);
INSERT INTO MENU VALUES('2', '카페라떼', 5000, 1, DEFAULT);
INSERT INTO MENU VALUES('3', '카페모카', 5500, 1, DEFAULT);
INSERT INTO MENU VALUES('4', '카라멜마끼아또', 5500, 1, DEFAULT);

COMMIT;
SELECT * FROM MENU;